[[language]]
name = "cpp"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
scope = "source.python"
language-servers = [ "pyright" ]
formatter = { command = "black", args = ["-"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "yaml"
file-types = ["yaml", "yml", "yamda"]
indent = { tab-width = 2, unit = "  " }

[language-server.rust-analyzer.config]
cargo.features = "all"
check.command = "clippy"
