#!/usr/bin/env bash
# Updates system and removes extra
# Sudo echo to get super user priviledges at start of script
set -e
sudo echo
if [ -f /etc/redhat-release ]; then
    distro="$(cat /etc/redhat-release)"
else
    distro="$(cat /etc/issue)"
fi
case "$distro" in
    *"Ubuntu"* )
        echo "Updating package lists..."
        sudo apt update -y
        echo
        echo "Updating any out-of-date packages..."
        sudo apt upgrade -y
        echo
        echo "Removing packages which are no longer needed..."
        sudo apt autoremove -y
        echo
        echo "Removing package cache..."
        sudo apt autoclean -y
        echo
        echo "Update complete." ;;
    *"CentOS"*|*"RHEL"* )
        sudo yum check-update -y
        sudo yum update -y ;;
    *"Arch"* )
        aurman -Syu --devel --noconfirm --noedit ;;
    * )
        echo "Unknown distro" ;;
esac
