#!/bin/bash
# Script for installing jupyter kernel in a virtual environment
# Environment kernel will be "Python {Python Version Number (2 | 3)} ({environment name})"
source "$HOME/.envs/$1/bin/activate"

pip install ipykernel
export PYTHON_VERSION=`python -c 'import sys; v = sys.version_info[0]; sys.stdout.write(str(v))'`
python -m ipykernel install --user --name "$1" --display-name "Python $PYTHON_VERSION ($1)"

